fix/NUM_MENU_ITEMS Conditionally check for NUM_MENU_ITEMS
This fix ensures that the NUM_MENU_ITEMS value is only checked
when USE_DYNAMIC_PARAMETERS is set to true.

Previously the compile would yell with a message
'error: 'NUM_MENU_ITEMS' was not declared in this scope
  341 |       if (NUM_MENU_ITEMS > 3)'